import type { AccessRecord, AuditLog } from "./types";

export const demoRecords: AccessRecord[] = [
  {
    id: "demo-1",
    holder_name: "AERO Building Manager",
    holder_type: "Building Manager",
    company: "AERO Apartments",
    contact_details: "building.manager@example.com",
    access_type: "Key only",
    access_area: "Common areas",
    purpose: "Routine common property management",
    approved_by: "AERO Committee",
    authority_source: "Committee approval",
    approval_reference: "Committee minutes 2026-04-01",
    approval_date: "2026-04-01",
    start_date: "2026-04-02",
    expiry_date: "2027-04-02",
    return_due_date: null,
    returned_date: null,
    status: "Active",
    conditions: "Access is limited to approved building management duties.",
    notes: "Safe demo label only. No codes or key cuts stored.",
    attachment_url: "",
    created_at: "2026-04-02T00:00:00Z",
    updated_at: "2026-05-12T00:00:00Z",
  },
  {
    id: "demo-2",
    holder_name: "FireSafe Services",
    holder_type: "Contractor",
    company: "FireSafe Services Pty Ltd",
    contact_details: "firesafe@example.com",
    access_type: "Contractor / temporary access",
    access_area: "Fire services area",
    purpose: "Scheduled fire services inspection",
    approved_by: "Strata Manager",
    authority_source: "Strata instruction",
    approval_reference: "Work order FS-2026-051",
    approval_date: "2026-05-01",
    start_date: "2026-05-06",
    expiry_date: "2026-06-02",
    return_due_date: "2026-06-03",
    returned_date: null,
    status: "Issued",
    conditions: "Access during business hours with sign-in required.",
    notes: "Contractor access set 01. No sensitive access details recorded.",
    attachment_url: "",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-20T00:00:00Z",
  },
  {
    id: "demo-3",
    holder_name: "Lift Consultant",
    holder_type: "Consultant",
    company: "Vertical Review Group",
    contact_details: "consultant@example.com",
    access_type: "Inspection access",
    access_area: "Plant room",
    purpose: "Independent lift plant review",
    approved_by: "Committee Secretary",
    authority_source: "Committee approval",
    approval_reference: "Committee resolution 2026-03-10",
    approval_date: "2026-03-10",
    start_date: "2026-03-15",
    expiry_date: "2026-04-15",
    return_due_date: "2026-04-16",
    returned_date: null,
    status: "Expired",
    conditions: "Escort required outside ordinary work hours.",
    notes: "Follow up requested with consultant.",
    attachment_url: "",
    created_at: "2026-03-10T00:00:00Z",
    updated_at: "2026-04-17T00:00:00Z",
  },
  {
    id: "demo-4",
    holder_name: "Committee Chair",
    holder_type: "Committee",
    company: "AERO Apartments Committee",
    contact_details: "chair@example.com",
    access_type: "Fob only",
    access_area: "Common areas",
    purpose: "Authorised representative access",
    approved_by: "AERO Committee",
    authority_source: "Committee approval",
    approval_reference: "Committee standing authority",
    approval_date: "2026-02-01",
    start_date: "2026-02-01",
    expiry_date: null,
    return_due_date: null,
    returned_date: "2026-05-05",
    status: "Returned",
    conditions: "Use only for committee duties.",
    notes: "Building access fob returned and logged.",
    attachment_url: "",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
];

export const demoAuditLog: AuditLog[] = [
  {
    id: "audit-demo-1",
    access_record_id: "demo-1",
    action: "Record created",
    details: "Initial access register entry created.",
    created_at: "2026-04-02T00:00:00Z",
    created_by: "demo",
  },
  {
    id: "audit-demo-2",
    access_record_id: "demo-2",
    action: "Status changed",
    details: "Marked issued for temporary contractor access.",
    created_at: "2026-05-20T00:00:00Z",
    created_by: "demo",
  },
  {
    id: "audit-demo-3",
    access_record_id: "demo-3",
    action: "Notes added",
    details: "Expired access and overdue return follow-up noted.",
    created_at: "2026-04-17T00:00:00Z",
    created_by: "demo",
  },
  {
    id: "audit-demo-4",
    access_record_id: "demo-4",
    action: "Returned",
    details: "Access item marked returned.",
    created_at: "2026-05-05T00:00:00Z",
    created_by: "demo",
  },
];
